# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

target :NendVideoMoPubCustomEventSample do

pod 'NendSDK_iOS_MoPub_CustomEvent'

end

target :NendVideoMoPubCustomEventSample_Swift do

pod 'NendSDK_iOS_MoPub_CustomEvent'

end
