# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target :NendMoPubCustomEventSample do

pod 'NendSDK_iOS_MoPub_CustomEvent'

end

target :NendMoPubCustomEventSwiftSample do

pod 'NendSDK_iOS_MoPub_CustomEvent'

end
